"milestones":
  - "title": "0.2.2"
    "description": "Patch release – targeting 0.2.x branch (semantic version: 0.2.2)"
    "state": "open"
  - "title": "0.3.0"
    "description": "Minor release – targeting 0.3.x branch (semantic version: 0.3.0)"
    "state": "open"
  - "title": "1.0.0"
    "description": "Major release – targeting 1.0.x branch (semantic version: 1.0.0)"
    "state": "open"
  - "title": "0.2.1"
    "description": "Patch release – targeting 0.2.x branch (semantic version: 0.2.1)"
    "state": "closed"
"repository":
  "name": "psalm-sandbox"
  "description": "Provides a framework for testing Psalm plugins"
  "topics": "dev, ghostwriter, psalm-plugin, psalm-plugin-tester, psalm-sandbox, testing"
  "homepage": "https://github.com/ghostwriter/psalm-sandbox"
  "default_branch": "0.2.x"
  "allow_auto_merge": true
  "allow_forking": true
  "allow_merge_commit": true
  "allow_rebase_merge": true
  "allow_squash_merge": true
  "allow_update_branch": true
  "delete_branch_on_merge": true
  "enable_automated_security_fixes": true
  "enable_vulnerability_alerts": true
  "has_downloads": true
  "has_issues": true
  "has_projects": false
  "has_wiki": false
  "security_and_analysis":
    "advanced_security":
      "status": "enabled"
    "code_security":
      "status": "enabled"
    "secret_scanning":
      "status": "enabled"
    "secret_scanning_ai_detection":
      "status": "enabled"
    "secret_scanning_non_provider_patterns":
      "status": "enabled"
    "secret_scanning_push_protection":
      "status": "enabled"
  "web_commit_signoff_required": true
